# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'
command_timeout = 5000
palette = "dracula"
scan_timeout = 300

[palettes.dracula]
background = "#282a36"
current_line = "#44475a"
foreground = "#f8f8f2"
comment = "#6272a4"
cyan = "#8be9fd"
green = "#50fa7b"
orange = "#ffb86c"
pink = "#ff79c6"
purple = "#bd93f9"
red = "#ff5555"
yellow = "#f1fa8c"

# starship preset plain-text-symbols
[c]
symbol = "C "

[cpp]
symbol = "C++ "

[character]
error_symbol = "[x](bold red)"
success_symbol = "[>](bold green)"

[cmake]
symbol = "cmake "

[directory]
fish_style_pwd_dir_length = 1
format = "in [$path]($style)[$read_only]($read_only_style) "
read_only = " ro"

[docker_context]
symbol = "docker "

[git_branch]
format = "at [$symbol$branch(:$remote_branch)]($style) "
symbol = ""

[git_commit]
tag_disabled = false
tag_symbol = " @ "

[git_status]
ahead = ">"
behind = "<"
deleted = "x"
diverged = "<>"
renamed = "r"

[golang]
symbol = "go "

[helm]
symbol = "helm "

[hostname]
format = "[$ssh_symbol$hostname]($style) "
ssh_symbol = "@"
trim_at = ""

[kubernetes]
disabled = false
format = "on [$symbol$context( \\[$namespace\\])]($style) "
style = "black bold"
symbol = ""

[[kubernetes.contexts]]
context_pattern = "(?P<cluster>qa-\\w+-\\d+)"
context_alias = "$cluster"
style = "orange bold"

[[kubernetes.contexts]]
context_pattern = "(?P<cluster>\\w+-\\w+-\\d+)"
context_alias = "$cluster"
style = "red bold"

[nodejs]
symbol = "js "

[package]
symbol = "pkg "

[python]
symbol = "py "

[ruby]
symbol = "rb "

[rust]
symbol = "rs "

[status]
symbol = "[x](bold red) "

[terraform]
symbol = "terraform "

[username]
format = "[$user]($style) "
show_always = true
